---
kind: pipeline
type: ssh
name: Ubuntu | Nginx + Apache2

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64

steps:
  - name: Download submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build LinkPanel package and install
    commands:
      - ./src/linkpnl_autocompile.sh --linkpanel --install '~localsrc'
  - name: Reset Web templates
    commands:
      - rm /usr/local/linkpanel/data/templates/web/nginx/php-fpm/*.*
      - rm /usr/local/linkpanel/data/templates/web/nginx/*.*
      - rm /usr/local/linkpanel/data/templates/web/apache2/php-fpm/*.*
      - rm /usr/local/linkpanel/data/templates/web/apache2/*.*
      - rm /usr/local/linkpanel/data/templates/web/php-fpm/*.*
      - /usr/local/linkpanel/bin/v-update-web-templates
  - name: Run system / user tests
    commands:
      - bats ./test/test.bats
  - name: Run restore tests
    commands:
      - bats ./test/restore.bats
  - name: Run config tests
    commands:
      - bats ./test/config-tests.bats

trigger:
  event: [pull_request, push]
  ref:
    - refs/heads/release
    - refs/heads/prerelease
    - refs/heads/servicing
    - refs/heads/tests/*
    - refs/heads/main
    - refs/pull/*/head

---
kind: pipeline
type: ssh
name: Debian | Nginx

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address2
  user:
    from_secret: username
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64

steps:
  - name: Download submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: Build LinkPanel package install
    commands:
      - ./src/linkpnl_autocompile.sh --linkpanel --install '~localsrc'
  - name: Reset Web templates
    commands:
      - rm /usr/local/linkpanel/data/templates/web/nginx/php-fpm/*.*
      - rm /usr/local/linkpanel/data/templates/web/nginx/*.*
      - rm /usr/local/linkpanel/data/templates/web/apache2/php-fpm/*.*
      - rm /usr/local/linkpanel/data/templates/web/apache2/*.*
      - rm /usr/local/linkpanel/data/templates/web/php-fpm/*.*
      - /usr/local/linkpanel/bin/v-update-web-templates
  - name: Run system / user tests
    commands:
      - bats ./test/test.bats
  - name: Run restore tests
    commands:
      - bats ./test/restore.bats
  - name: Run config tests
    commands:
      - bats ./test/config-tests.bats
  - name: Run Letsencrypt test against Staging
    commands:
      - cp /root/le-env.sh /tmp/linkpanel-le-env.sh
      - bats ./test/letsencrypt.bats

trigger:
  event: [pull_request, push]
  ref:
    - refs/heads/release
    - refs/heads/prerelease
    - refs/heads/servicing
    - refs/heads/tests/*
    - refs/heads/main
    - refs/pull/*/head

---
kind: pipeline
type: docker
name: Push to beta atp server

platform:
  os: linux
  arch: amd64

steps:
  - name: Build JS/CSS
    image: node:current-slim
    commands:
      - npm ci --ignore-scripts
      - npm run build
  - name: Build
    image: debian:bookworm
    commands:
      - ln -snf /etc/localtime && echo CET > /etc/timezone
      - ./src/linkpnl_autocompile.sh --dontinstalldeps --linkpanel --debug --cross --noinstall --keepbuild '~localsrc'
      - mkdir -p ./linkpanel/
      - mv /tmp/linkpanelcp-src/deb/*.deb ./linkpanel/
  - name: Upload
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: apt_server
      user: root
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root/
      source:
        - ./linkpanel/*

trigger:
  event: [promote]
