#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Touch and set permisions on default log files on installation
update-rc.d linkpanel defaults > /dev/null
invoke-rc.d linkpanel start || true

# Adapt Port Listing in LINKPANEL NGINX Backend
source /usr/local/linkpanel/func/syshealth.sh # Load syshealth functions
syshealth_adapt_linkpanel_nginx_listen_ports  # Adapt port listing
syshealth_adapt_nginx_resolver

# Run triggers only on updates
if [ ! -e "/usr/local/linkpanel/data/users/" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LINKPANEL" ]; then
	export LINKPANEL='/usr/local/linkpanel'
	PATH=$PATH:/usr/local/linkpanel/bin
	export PATH
fi

# Check if preinstall hook exists
if [ -e "/etc/linkpanelcp/hooks/nginx/pre_install.sh" ]; then
	/etc/linkpanelcp/hooks/nginx/pre_install.sh
fi

# Load upgrade functions and variables
source /usr/local/linkpanel/func/main.sh
source /usr/local/linkpanel/func/upgrade.sh
source /usr/local/linkpanel/conf/linkpanel.conf
source /usr/local/linkpanel/install/upgrade/upgrade.conf

# Reset backend port
if [ -n "$BACKEND_PORT" ]; then
	/usr/local/linkpanel/bin/v-change-sys-port $BACKEND_PORT
fi

if [ -e "/etc/linkpanelcp/hooks/nginx/post_install.sh" ]; then
	/etc/linkpanelcp/hooks/nginx/post_install.sh
fi

# Restart linkpanel service
if [ -f "/etc/init.d/linkpanel" ]; then
	systemctl restart linkpanel > /dev/null 2>&1
fi
