#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/linkpanel/data/users/" ]; then
	exit
fi

# Check if preinstall hook exists
if [ -e "/etc/linkpanelcp/hooks/php/pre_install.sh" ]; then
	/etc/linkpanelcp/hooks/php/pre_install.sh
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LINKPANEL" ]; then
	export LINKPANEL='/usr/local/linkpanel'
	PATH=$PATH:/usr/local/linkpanel/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/linkpanel/func/main.sh
source /usr/local/linkpanel/func/upgrade.sh
source /usr/local/linkpanel/conf/linkpanel.conf
source /usr/local/linkpanel/install/upgrade/upgrade.conf

# Restart linkpanel service
if [ -f "/etc/init.d/linkpanel" ]; then
	systemctl restart linkpanel > /dev/null 2>&1
fi

# Check if preinstall hook exists
if [ -e "/etc/linkpanelcp/hooks/php/post_install.sh" ]; then
	/etc/linkpanelcp/hooks/php/post_install.sh
fi
