#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/linkpanel/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$LINKPANEL" ]; then
	export LINKPANEL='/usr/local/linkpanel'
	PATH=$PATH:/usr/local/linkpanel/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/linkpanel/func/main.sh
source /usr/local/linkpanel/func/upgrade.sh
source /usr/local/linkpanel/conf/linkpanel.conf
source /usr/local/linkpanel/install/upgrade/upgrade.conf

# Restart linkpanel-web-terminal service if enabled
if [ -f "/etc/systemd/system/linkpanel-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled linkpanel-web-terminal > /dev/null 2>&1; then
		systemctl restart linkpanel-web-terminal
	fi
fi
